const $=id=>document.getElementById(id);
const INR=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const CFG={backendUrl:'',accessKey:'',selectedU:'NIFTY',selectedExpiry:'',side:'BUY',...JSON.parse(localStorage.getItem('tradepilotV3cfg')||'{}')};
let C=CFG,M={connected:false,underlyings:{},chain:[],selected:null,timer:null},P={account:{equity:100000,available:100000,openPnl:0,realized:0},positions:[],orders:[],rules:[]};
function saveCfg(){localStorage.setItem('tradepilotV3cfg',JSON.stringify(C))}
function backend(){return String(C.backendUrl||'').replace(/\/$/,'')}
async function api(path,opts={}){if(!backend())throw new Error('Set your private backend URL first.');const headers={'Content-Type':'application/json','X-TradePilot-Key':C.accessKey||'',...(opts.headers||{})};const r=await fetch(backend()+path,{cache:'no-store',...opts,headers});let d;try{d=await r.json()}catch{d={error:'Invalid backend response'}}if(!r.ok)throw new Error(d.error||d.message||`HTTP ${r.status}`);return d}
function paintMoney(el,v){el.textContent=INR(v);el.classList.toggle('green',v>0);el.classList.toggle('redtxt',v<0)}
function drawAccount(){paintMoney($('equity'),P.account?.equity??100000);paintMoney($('available'),P.account?.available??100000);paintMoney($('openPnl'),P.account?.openPnl??0);paintMoney($('realized'),P.account?.realized??0)}
function fmtChange(q){if(!q||!Number.isFinite(Number(q.ltp)))return ['—','Waiting for Angel One','muted'];const c=Number(q.netChange||0),pct=Number(q.percentChange||0);return [INR(q.ltp),(c>=0?'+':'')+c.toFixed(2)+' ('+(pct>=0?'+':'')+pct.toFixed(2)+'%)',c>=0?'green':'redtxt']}
function drawUnderlyings(){for(const [k,px,chg] of [['NIFTY','niftyPx','niftyChg'],['BANKNIFTY','bankPx','bankChg']]){const [a,b,c]=fmtChange(M.underlyings[k]);$(px).textContent=a;$(chg).textContent=b;$(chg).className='mini '+c}$('niftyCard').classList.toggle('active',C.selectedU==='NIFTY');$('bankCard').classList.toggle('active',C.selectedU==='BANKNIFTY')}
function drawConnection(msg=''){const b=$('liveBadge');if(M.connected){b.textContent='Angel One: LIVE';b.className='pill live';$('connectionNotice').className='notice good';$('connectionNotice').textContent=msg||'Connected to your private backend. Market prices and paper automation run on the server, even when this phone screen is closed.'}else{b.textContent='Angel One: not connected';b.className='pill off';$('connectionNotice').className='notice';$('connectionNotice').textContent=msg||'The phone app is hosted on GitHub Pages. Angel One credentials stay only on your private backend server.'}}
function drawSelected(){const c=M.selected;if(!c){$('selectedContract').textContent='Tap a CE or PE in the option chain';$('selectedContract').className='symbolbox muted';$('placeOrder').disabled=true;return}$('selectedContract').innerHTML=`<b>${c.tradingSymbol}</b><br><span class="mini muted">${c.expiry} • ${c.optionType} • LTP ${INR(c.ltp)} • lot ${c.lotSize||'—'}</span>`;$('selectedContract').className='symbolbox';$('qty').placeholder=c.lotSize?`lot ${c.lotSize}`:'quantity';$('placeOrder').disabled=!M.connected;updateOrderButton()}
function updateOrderButton(){const side=C.side||'BUY',b=$('placeOrder');b.textContent=side+' — PAPER ORDER';b.className='full '+(side==='BUY'?'buy':'sell');$('buyTab').classList.toggle('active',side==='BUY');$('sellTab').classList.toggle('active',side==='SELL')}
function drawChain(){const root=$('chain');if(!M.chain.length){root.innerHTML='<div class="empty">No option contracts loaded.</div>';return}const by={};for(const c of M.chain){by[c.strike]??={};by[c.strike][c.optionType]=c}const rows=Object.entries(by).sort((a,b)=>Number(a[0])-Number(b[0]));root.innerHTML=rows.map(([strike,o])=>{const ce=o.CE,pe=o.PE;const btn=c=>c?`<div class="contract" data-token="${c.token}"><div class="ltp">${INR(c.ltp)}</div><small>${c.tradingSymbol}</small></div>`:'<div></div>';return `<div class="chainRow">${btn(ce)}<div class="mini muted">CE</div><div class="strike">${Number(strike).toLocaleString('en-IN')}</div><div class="mini muted" style="text-align:right">PE</div>${btn(pe)}</div>`}).join('');root.querySelectorAll('.contract').forEach(x=>x.onclick=()=>{M.selected=M.chain.find(c=>String(c.token)===x.dataset.token);drawSelected()})}
function drawPositions(){const root=$('positions');if(!P.positions?.length){root.innerHTML='<div class="empty">No open positions.</div>';return}root.innerHTML=P.positions.map(p=>`<div class="position"><div class="positionTop"><div><b>${p.side} ${p.tradingSymbol}</b><div class="mini muted">${p.qty} qty • Entry ${INR(p.entry)} • LTP ${INR(p.ltp)}</div></div><b class="${Number(p.pnl)>=0?'green':'redtxt'}">${INR(p.pnl)}</b></div><div class="mini muted">SL ${p.sl?INR(p.sl):'—'} • Target ${p.target?INR(p.target):'—'} • ${p.source}</div><div class="positionActions"><button class="ghost" data-exit="${p.id}">EXIT PAPER POSITION</button></div></div>`).join('');root.querySelectorAll('[data-exit]').forEach(b=>b.onclick=()=>exitPosition(b.dataset.exit))}
function drawRules(){const root=$('rules');if(!P.rules?.length){root.innerHTML='<div class="empty">No automation rules armed.</div>';return}root.innerHTML=P.rules.map(r=>`<div class="position"><div class="positionTop"><b>${r.side} ${r.tradingSymbol}</b><button class="ghost" style="max-width:80px;padding:6px" data-cancel="${r.id}">Cancel</button></div><div class="mini muted">${r.triggerType==='NOW'?'Next live price':r.triggerType+' '+INR(r.triggerPrice)} • Qty ${r.qty} • SL ${r.sl||'—'} • Target ${r.target||'—'} • ${r.status}</div></div>`).join('');root.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>cancelRule(b.dataset.cancel))}
function drawOrders(){const root=$('orders');if(!P.orders?.length){root.innerHTML='<tr><td colspan="7" class="empty">No paper orders yet.</td></tr>';return}root.innerHTML=P.orders.slice().reverse().slice(0,60).map(o=>`<tr><td>${o.time||'—'}</td><td>${o.symbol}</td><td class="${o.side==='BUY'?'green':'redtxt'}">${o.side}</td><td>${o.qty}</td><td>${INR(o.price)}</td><td>${o.status}</td><td class="${Number(o.pnl||0)>=0?'green':'redtxt'}">${o.pnl==null?'—':INR(o.pnl)}</td></tr>`).join('')}
function drawAll(){drawAccount();drawUnderlyings();drawConnection();drawSelected();drawPositions();drawRules();drawOrders()}
async function state(){const d=await api('/api/paper/state');P=d;drawAccount();drawPositions();drawRules();drawOrders()}
async function exitPosition(id){try{await api('/api/paper/exit',{method:'POST',body:JSON.stringify({id})});await state()}catch(e){alert(e.message)}}
async function cancelRule(id){try{await api('/api/paper/rule/cancel',{method:'POST',body:JSON.stringify({id})});await state()}catch(e){alert(e.message)}}
async function ping(){try{const d=await api('/api/config');M.connected=!!d.configured;if(!M.connected){drawConnection('Backend reached, but Angel One credentials are not configured on the private server.');return}await Promise.all([loadMarket(),state()]);await loadExpiries();drawAll()}catch(e){M.connected=false;drawAll();drawConnection('Backend connection failed: '+e.message)} }
async function loadMarket(){const d=await api('/api/underlyings');M.underlyings=d.data||{};drawUnderlyings()}
async function loadExpiries(){const d=await api('/api/expiries?underlying='+encodeURIComponent(C.selectedU));const old=C.selectedExpiry;$('expiry').innerHTML=(d.expiries||[]).map(x=>`<option value="${x}">${x}</option>`).join('')||'<option value="">No expiries</option>';C.selectedExpiry=(d.expiries||[]).includes(old)?old:(d.expiries||[])[0]||'';$('expiry').value=C.selectedExpiry;saveCfg();if(C.selectedExpiry)await loadChain()}
async function loadChain(){if(!M.connected||!C.selectedExpiry)return;const root=$('chain');root.innerHTML='<div class="empty"><span class="spinner"></span> Loading Angel One option prices…</div>';try{const d=await api('/api/options?underlying='+encodeURIComponent(C.selectedU)+'&expiry='+encodeURIComponent(C.selectedExpiry)+'&width='+encodeURIComponent($('width').value));M.chain=d.contracts||[];if(d.spot)M.underlyings[C.selectedU]=d.spot;drawChain();drawUnderlyings()}catch(e){root.innerHTML='<div class="empty redtxt">'+e.message+'</div>'}}
async function tick(){if(!M.connected)return;try{await Promise.all([loadMarket(),state()]);if(C.selectedExpiry)await loadChain()}catch{}}
async function selectUnderlying(u){C.selectedU=u;M.selected=null;saveCfg();drawAll();if(M.connected)await loadExpiries()}
$('niftyCard').onclick=()=>selectUnderlying('NIFTY');$('bankCard').onclick=()=>selectUnderlying('BANKNIFTY');
$('expiry').onchange=()=>{C.selectedExpiry=$('expiry').value;saveCfg();loadChain()};$('width').onchange=loadChain;
$('buyTab').onclick=()=>{C.side='BUY';saveCfg();updateOrderButton()};$('sellTab').onclick=()=>{C.side='SELL';saveCfg();updateOrderButton()};
$('orderType').onchange=()=>{$('limitBox').style.display=$('orderType').value==='LIMIT'?'block':'none'};
$('placeOrder').onclick=async()=>{if(!M.selected)return;const qty=num($('qty').value);if(!qty)return alert('Enter quantity.');const body={side:C.side,contract:M.selected,qty,orderType:$('orderType').value,limitPrice:num($('limitPrice').value),sl:num($('sl').value),target:num($('target').value)};try{await api('/api/paper/order',{method:'POST',body:JSON.stringify(body)});await state()}catch(e){alert(e.message)}};
$('runCommand').onclick=async()=>{const text=$('command').value.trim();if(!text)return;try{const d=await api('/api/paper/command',{method:'POST',body:JSON.stringify({command:text,expiry:C.selectedExpiry||null})});$('commandResult').textContent=d.message||'Command accepted.';$('commandResult').className='notice good';await state()}catch(e){$('commandResult').textContent='Command rejected: '+e.message;$('commandResult').className='notice bad'}};
$('backendUrl').value=C.backendUrl||'';$('accessKey').value=C.accessKey||'';
$('saveBackend').onclick=()=>{const v=$('backendUrl').value.trim(),k=$('accessKey').value;if(v&&!/^https:\/\//i.test(v)&&!/^http:\/\/localhost/i.test(v))return alert('Use an HTTPS backend URL. HTTP is allowed only for localhost during development.');C.backendUrl=v;C.accessKey=k;saveCfg();ping()};
$('refreshChain').onclick=()=>M.connected?loadChain():ping();$('resetAccount').onclick=async()=>{if(!confirm('Reset the server-side paper account to ₹1,00,000 and erase paper trades/rules?'))return;try{await api('/api/paper/reset',{method:'POST',body:'{}'});await state()}catch(e){alert(e.message)}};
$('goPositions').onclick=()=>document.getElementById('positions').scrollIntoView({behavior:'smooth'});$('goConsole').onclick=()=>document.getElementById('command').scrollIntoView({behavior:'smooth',block:'center'});$('goSettings').onclick=()=>document.getElementById('settings').scrollIntoView({behavior:'smooth'});
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installBtn').style.display='block'});$('installBtn').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installBtn').style.display='none'};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
drawAll();updateOrderButton();if(C.backendUrl)ping();M.timer=setInterval(tick,3000);
